import { Product } from './types';

export const ALL_PRODUCTS: Product[] = [
  { id: 'PMI001', name: 'PE Lengkung Everyday 15*30*0.06', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI002', name: 'PE Lengkung Everyday 15*30*0.06 new', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI003', name: 'PE Lengkung Everyday 17.5*30*0.06', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI004', name: 'PE Lengkung Everyday 17.5*33*0.06 new', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI005', name: 'PE Lengkung All Natural 17.5*40*0.06 new', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI006', name: 'PE Lengkung Natural 18.5*33*0.06', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI007', name: 'PE Lengkung Family Feast 18.5*40*0.6', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI008', name: 'PE Lengkung Family Feast 20*35*0.05', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI009', name: 'PE Lengkung 15*35*0.06 (Drop 1-4)', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI010', name: 'PE Lengkung 17*35*0.06 (Drop 5-7)', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI011', name: 'PE 23*35*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI012', name: 'PE lengkung 18.5*33*0.05 (Drop 8-9)', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI013', name: 'PE lengkung 20*35*0.06 (Drop 10)', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI014', name: 'PE 17*35*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI015', name: 'PE 17*40*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI016', name: 'PE 15*25*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI017', name: 'PE 15*25*0.10', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI018', name: 'PE 17*28*0.10', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI019', name: 'PE 40*60*0.04', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI020', name: 'PE 40*80*0.06', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI021', name: 'PE 85/55 *64*0.04', unit: 'Kg', category: 'Packaging' },
  { id: 'PMI022', name: 'PE 60/40 *80*0.04', unit: 'Kg', category: 'Packaging' },
  { id: 'PME002', name: 'PE Lengkung Farmnest 16.5*30*0.11 (898009)', unit: 'Kg', category: 'Packaging' },
  { id: 'PME003', name: 'PE Lengkung Farmnest 16.5*30*0.11 (898011)', unit: 'Kg', category: 'Packaging' },
  { id: 'PME004', name: 'MyChicken 12*36', unit: 'Kg', category: 'Packaging' },
  { id: 'PME005', name: 'MyChicken 14*36', unit: 'Kg', category: 'Packaging' },
  { id: 'PME006', name: 'MyChicken 17*36', unit: 'Kg', category: 'Packaging' },
  { id: 'PME018', name: 'MyChicken 13*30', unit: 'Kg', category: 'Packaging' },
  { id: 'PME019', name: 'MyChicken 16*30', unit: 'Kg', category: 'Packaging' },
  { id: 'PME007', name: 'Plastik CFC', unit: 'Kg', category: 'Packaging' },
  { id: 'PME008', name: 'Plastik Ayamkoe', unit: 'Pcs', category: 'Packaging' },
  { id: 'PME009', name: 'Plastik Lazatto Hitam', unit: 'Kg', category: 'Packaging' },
  { id: 'PME010', name: 'Plastik Dkriuk', unit: 'Kg', category: 'Packaging' },
  { id: 'PME011', name: 'Plastik Thalita', unit: 'Pcs', category: 'Packaging' },
  { id: 'PMI023', name: 'Pouch Bounty dengan zipper', unit: 'Karton', category: 'Packaging' },
  { id: 'PMI024', name: 'Karung Cut up', unit: 'Pcs', category: 'Packaging' },
  { id: 'PMI025', name: 'Karung Polos', unit: 'Pcs', category: 'Packaging' },
  { id: 'PMI026', name: 'Karung Premium', unit: 'Pcs', category: 'Packaging' },
  { id: 'PMI027', name: 'Karung Standard', unit: 'Pcs', category: 'Packaging' },
  { id: 'PMI028', name: 'Bounty Hitam 17*30', unit: 'Pcs', category: 'Packaging' },
  { id: 'PME012', name: 'Karung MyChicken', unit: 'Pcs', category: 'Packaging' },
  { id: 'PME013', name: 'Plastik PE 40x60 Tomat', unit: 'Pack', category: 'Packaging' },
  { id: 'PME014', name: 'Sagala Ori 17*35*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PME015', name: 'Sagala Spicy 17*35*0.08', unit: 'Kg', category: 'Packaging' },
  { id: 'PME016', name: 'Karton Bounty 400x300x200', unit: 'Pcs', category: 'Other' },
  { id: 'PME017', name: 'Karton Polos Indomaret', unit: 'Pcs', category: 'Other' },
  { id: 'OMI001', name: 'Sticker Barcode 70x40mm', unit: 'Roll', category: 'Other' },
  { id: 'OMI002', name: 'Ribbon full resin', unit: 'Roll', category: 'Other' },
  { id: 'OMI003', name: 'Benang jahit karung', unit: 'Pcs', category: 'Other' },
  { id: 'OMI004', name: 'Solasi Bening Bounty', unit: 'Pcs', category: 'Other' },
  { id: 'OMI005', name: 'Sarung tangan plastik', unit: 'Pcs', category: 'Other' },
  { id: 'OMI006', name: 'Sticker astro Boneles paha', unit: 'Pcs', category: 'Other' },
  { id: 'OMI007', name: 'Sticker astro Boneles dada', unit: 'Pcs', category: 'Other' },
  { id: 'OMI008', name: 'Sticker Barcode 50x20mm', unit: 'Roll', category: 'Other' },
  { id: 'OMI009', name: 'Solasi Merah', unit: 'Roll', category: 'Other' },
  { id: 'OMI010', name: 'Solasi Kuning', unit: 'Roll', category: 'Other' },
  { id: 'OMI011', name: 'Sticker Barcode 60 x 30mm Core', unit: 'Roll', category: 'Other' },
  { id: 'OME001', name: 'Solasi Bening Indomaret', unit: 'Pcs', category: 'Other' },
  { id: 'OME002', name: 'Stiker Astro BSB', unit: 'Lembar', category: 'Other' },
  { id: 'OME003', name: 'Stiker Astro Dada Utuh', unit: 'Lembar', category: 'Other' },
  { id: 'OME004', name: 'Stiker Astro Paha Bawah', unit: 'Lembar', category: 'Other' },
  { id: 'OME005', name: 'Stiker Astro Kulit', unit: 'Lembar', category: 'Other' },
  { id: 'OME006', name: 'Stiker Astro Paha Utuh', unit: 'Lembar', category: 'Other' },
  { id: 'OME007', name: 'Stiker Astro BSL', unit: 'Lembar', category: 'Other' },
  { id: 'OME008', name: 'Stiker Astro Sayap', unit: 'Lembar', category: 'Other' },
  { id: 'OME009', name: 'Stiker Astro Ceker', unit: 'Lembar', category: 'Other' },
  { id: 'OME010', name: 'Stiker Astro Cutup', unit: 'Lembar', category: 'Other' },
  { id: 'OME011', name: 'Stiker Astro Paha Atas', unit: 'Lembar', category: 'Other' },
  { id: 'OME012', name: 'Stiker Osave Dada', unit: 'Lembar', category: 'Other' },
  { id: 'OME013', name: 'Stiker Osave Sayap', unit: 'Lembar', category: 'Other' },
  { id: 'OME014', name: 'Stiker Osave Paha Atas', unit: 'Lembar', category: 'Other' },
  { id: 'OME015', name: 'Stiker Osave Paha Bawah', unit: 'Lembar', category: 'Other' },
  { id: 'PMI029', name: 'Karton Bounty 400X300X270', unit: 'Pcs', category: 'Other' },
  { id: 'PMI030', name: 'Tray Kuning', unit: 'Pcs', category: 'Other' },
  { id: 'IME001', name: 'Bumbu DFresto', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME002', name: 'Bumbu Wendy\'s/MCR', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME003', name: 'Bumbu Dr. Chicken', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME004', name: 'Bumbu ASI', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME005', name: 'Bumbu Marinade CR802/AB', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME006', name: 'Bumbu D Chick Regular', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME007', name: 'Bumbu CFC', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME008', name: 'Bumbu lazatto ori', unit: 'Pack', category: 'Ingredients' },
  { id: 'IME009', name: 'Bumbu Ayam Guling Majos', unit: 'Kg', category: 'Ingredients' },
  { id: 'IMI001', name: 'Bumbu IRS Inject Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'IMI002', name: 'Bumbu IRS Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'IMI003', name: 'Bumbu Gochujang marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'IMI004', name: 'Bumbu Italian chicken', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME010', name: 'Bumbu Amazing Reguler', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME011', name: 'Bumbu marinade powder', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME012', name: 'Bumbu AB chicken', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME013', name: 'Bumbu berkah sinergi', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME014', name: 'Bumbu Golden lamian', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME015', name: 'Bumbu DKriuk', unit: 'Pack', category: 'Ingredients' },
  { id: 'IME016', name: 'Bumbu Thalita CR802 (Rudy)', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME017', name: 'Bumbu Mindo', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME018', name: 'Madu', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME019', name: 'Bumbu Hisana', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME020', name: 'Bumbu Keren Yes', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME021', name: 'Bumbu Hungry', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME022', name: 'Bumbu Indian', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME023', name: 'Bumbu Indomaret KRW', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME024', name: 'Bumbu Chicago', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME025', name: 'Bumbu Hoops', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME026', name: 'Bumbu Ranisa', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME027', name: 'Bumbu BEFC', unit: 'Pack', category: 'Ingredients' },
  { id: 'IME028', name: 'Bumbu MR Razik', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME029', name: 'Bumbu Mr Kriuk', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME030', name: 'Bumbu Alabama Merah', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME031', name: 'Bumbu Labbaik', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME032', name: 'Bumbu Sagala Katsu Original', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME033', name: 'Bumbu Sagala Hot Spicy', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME034', name: 'Bumbu Sagala Ori', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME035', name: 'Bumbu Krenchise', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME036', name: 'Bumbu Topychick', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME037', name: 'Bumbu CMM (Hangry)', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME040', name: 'Garam Hangry', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME038', name: 'Meat Texture Improver', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME039', name: 'Bumbu Mr Chicko', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME041', name: 'BK Regular Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME042', name: 'BK Bone In Chicken Spicy Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME043', name: 'BK Spicy Marinade Kerry', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME044', name: 'BK Modified Starch', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME045', name: 'BK Sodium Tripolyphosphate', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME046', name: 'Bumbu Mutiara Tri Saka', unit: 'Kg', category: 'Ingredients' },
  { id: 'CMI001', name: 'Vosen Spartec', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI002', name: 'Vosen Diverfoam', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI003', name: 'Vosen Hand Clean', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI004', name: 'Vosen Isora Clean', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI005', name: 'Round Up Obat Rumput', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI006', name: 'Rom Krom', unit: 'Ember', category: 'Chemical' },
  { id: 'CMI007', name: 'Propyline Glycol', unit: 'Drum', category: 'Chemical' },
  { id: 'CMI008', name: 'Oli Mycom Compressor', unit: 'Drum', category: 'Chemical' },
  { id: 'CMI009', name: 'Karbon', unit: 'Sak', category: 'Chemical' },
  { id: 'PMI031', name: 'Tray Hitam', unit: 'Pcs', category: 'Packaging' },
  { id: 'IME047', name: 'Bumbu Crisbar', unit: 'Kg', category: 'Ingredients' },
  { id: 'OME016', name: 'Stiker Osave Hati', unit: 'Lembar', category: 'Other' },
  { id: 'OME017', name: 'Stiker Osave Ceker', unit: 'Lembar', category: 'Other' },
  { id: 'OME018', name: 'Stiker Osave Ampela', unit: 'Lembar', category: 'Other' },
  { id: 'OME019', name: 'Stiker Osave BSB', unit: 'Lembar', category: 'Other' },
  { id: 'OME020', name: 'Stiker Osave Kulit', unit: 'Lembar', category: 'Other' },
  { id: 'IME048', name: 'Bumbu KAF Hot Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'PME020', name: 'Plastik KAF', unit: 'Kg', category: 'Packaging' },
  { id: 'IME049', name: 'Bumbu Tiga Karya Satria (TKS)', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME050', name: 'Bumbu J Chicken', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME051', name: 'Bumbu Karisma (KAEF)', unit: 'Kg', category: 'Ingredients' },
  { id: 'PME021', name: 'Plastik Merah (Dbesto)', unit: 'Kg', category: 'Packaging' },
  { id: 'IME052', name: 'Bumbu Ayam Mrothol', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME053', name: 'Bumbu BK Rempah Marinade', unit: 'Kg', category: 'Ingredients' },
  { id: 'CMI010', name: 'MT Anbac', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI011', name: 'MT Chloran', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI012', name: 'MT Klin 180 S', unit: 'Liter', category: 'Chemical' },
  { id: 'CMI013', name: 'MT Klin 100', unit: 'Liter', category: 'Chemical' },
  { id: 'OMI012', name: 'Sticker Barcode 100x70mm', unit: 'Pcs', category: 'Other' },
  { id: 'IME054', name: 'Bumbu Indomaret CB', unit: 'Kg', category: 'Ingredients' },
  { id: 'CMI014', name: 'MT Hand Soft', unit: 'Liter', category: 'Chemical' },
  { id: 'OMI013', name: 'Hot Ink Roll', unit: 'Pcs', category: 'Other' },
  { id: 'IME055', name: 'Bumbu Alabama Putih', unit: 'Kg', category: 'Ingredients' },
  { id: 'OME021', name: 'Tusuk Sate', unit: 'Pack', category: 'Other' },
  { id: 'OME022', name: 'Stiker Osave Sate Ayam', unit: 'Pcs', category: 'Other' },
  { id: 'IME056', name: 'Bumbu Thalita 7RSS68B (IRS)', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME057', name: 'Bumbu Thalita EF 76 (Ranisa)', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME058', name: 'Bumbu Dikichi Regular', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME059', name: 'Bumbu Dikichi Hot', unit: 'Kg', category: 'Ingredients' },
  { id: 'IME060', name: 'Bumbu D\'Roasting', unit: 'Kg', category: 'Ingredients' }
];